# Generated by Django 6.0.6 on 2026-07-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidades'), ('KG', 'Kilogramos'), ('LTS', 'Litros')], max_length=10)),
                ('categoria', models.CharField(choices=[('BARRA', 'Barra'), ('COCINA', 'Cocina'), ('EMPAQUES', 'Empaques'), ('INSUMOS', 'Insumos')], max_length=50)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('MERMA', 'Merma')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.operario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventario.producto')),
            ],
        ),
    ]
