# Generated by Django 6.0.6 on 2026-07-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_movimiento_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='operario',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
