# Generated by Django 6.0.6 on 2026-07-04 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_operario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
