# Generated by Django 6.0.6 on 2026-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
