from django.core.management.base import BaseCommand
from inventario.models import Producto

class Command(BaseCommand):
    help = 'Carga inicial de productos en la base de datos'

    def handle(self, *args, **kwargs):
        # PEGA AQUÍ TU LISTA DE PRODUCTOS (Ejemplo de estructura)
        # Asegúrate de usar los values exactos de CATEGORIAS y UNIDADES definidos en models.py
        # CATEGORIAS: 'BARRA', 'COCINA', 'EMPAQUES', 'INSUMOS'
        # UNIDADES: 'UND', 'KG', 'LTS'
        PRODUCTOS_A_CARGAR = [
    # --- COCINA / ALIMENTOS ---
    {"codigo": 1001, "descripcion": "ACEITE 20 L", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1002, "descripcion": "ACEITE BALSÁMICO", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1003, "descripcion": "ACEITE DE OLIVA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1004, "descripcion": "ALBONDIGAS", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1005, "descripcion": "ALCAPARRAS", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1006, "descripcion": "ANCHOAS", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1007, "descripcion": "ARROZ 5 KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1008, "descripcion": "AZUCAR 5 KG GUABIRA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1009, "descripcion": "AZUCAR MORENA 1 KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1010, "descripcion": "AZUCAR MORENA 5 KG GUABIRA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1011, "descripcion": "BANANA PORCIONADA 130GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1012, "descripcion": "CARNE MOLIDA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1013, "descripcion": "CEBOLLA MORADA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1014, "descripcion": "CHAMPIÑON", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1015, "descripcion": "CHEDDAR", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1016, "descripcion": "CIABATTA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1017, "descripcion": "COCOA 500GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1018, "descripcion": "CREMA DE AVELLANA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1019, "descripcion": "CREMA DE LECHE", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1020, "descripcion": "CREMA REPOSTERA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1021, "descripcion": "CROISSANT", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1022, "descripcion": "CUÑAPÉ", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1023, "descripcion": "DULCE DE LECHE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1024, "descripcion": "DURAZNO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1025, "descripcion": "DURAZNO ENLATADO", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1026, "descripcion": "EMPANADA DE GUAYABA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1027, "descripcion": "EMPANADA DE RICOTA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1028, "descripcion": "FIDEO 10 KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1029, "descripcion": "FRUTILLA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1030, "descripcion": "FRUTOS ROJOS 140GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1031, "descripcion": "GALLETA CHAMPANERA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1032, "descripcion": "GRANOLA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1033, "descripcion": "GUAYABADA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1034, "descripcion": "HAMBURGUESA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1035, "descripcion": "HARINA 1KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1036, "descripcion": "HONGO SECO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1037, "descripcion": "HUEVO", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1038, "descripcion": "HUMO LIQUIDO", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1039, "descripcion": "JAMON SERRANO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1040, "descripcion": "JAMON YORK", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1041, "descripcion": "KETCHUP EN BOLSA 2.8KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1042, "descripcion": "LECHE", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1043, "descripcion": "LECHE CONDENSADA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1044, "descripcion": "LECHE DE ALMENDRA", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1045, "descripcion": "LECHE EVAPORADA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1046, "descripcion": "LECHUGA CRESPA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1047, "descripcion": "LECHUGA MORADA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1048, "descripcion": "LIMONES", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1049, "descripcion": "LOMITO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1050, "descripcion": "MANGO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1051, "descripcion": "MANTEQUILLA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1052, "descripcion": "MANZANA VERDE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1053, "descripcion": "MARGARINA REINA 820GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1054, "descripcion": "MASA MADRE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1055, "descripcion": "MAYONESA EN BOLSA 2.8KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1056, "descripcion": "MEDIA LUNA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1057, "descripcion": "MERMA DE POLLO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1058, "descripcion": "MIEL", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1059, "descripcion": "MIEL DE MAPLE", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1060, "descripcion": "MOSTARDA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1061, "descripcion": "MOSTAZA EN BOLSA 2.8KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1062, "descripcion": "MOSTAZA EN POTE", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1063, "descripcion": "MOZZARELLA EN BARRA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1064, "descripcion": "MOZZARELLA LAMINADA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1065, "descripcion": "NARANJA DESHIDRATADA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1066, "descripcion": "OREO", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1067, "descripcion": "PALTA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1068, "descripcion": "PAN HAMBURGUESA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1069, "descripcion": "PAN MOLIDO 500GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1070, "descripcion": "PAPA HOLANDESA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1071, "descripcion": "PAPA FRITA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1072, "descripcion": "PEPINILLOS", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1073, "descripcion": "PEPPERONI", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1074, "descripcion": "PERA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1075, "descripcion": "PERNIL", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1076, "descripcion": "PIÑA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1077, "descripcion": "PIZZAS", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1078, "descripcion": "PULPA DE COCO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1079, "descripcion": "QUESO BONLE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1080, "descripcion": "QUINOA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1081, "descripcion": "RABANITO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1082, "descripcion": "RUCULA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1083, "descripcion": "SAL 5 KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1084, "descripcion": "SALSA CHOCOLATE", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1085, "descripcion": "SALSA DULCE DE LECHE", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1086, "descripcion": "SALSA FRUTILLA", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1087, "descripcion": "SALSA SOYA 5L", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1088, "descripcion": "SUCARYL CAJA", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1089, "descripcion": "TAMAL", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1090, "descripcion": "TOCINO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1091, "descripcion": "TOMATE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1092, "descripcion": "TOMATE CHERRY AMARILLO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1093, "descripcion": "TOMATE CHERRY ROJO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1094, "descripcion": "YOGUR GRIEGO", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1095, "descripcion": "ZANAHORIA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1096, "descripcion": "AZUCAR 5,5 KG AGUAI", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1097, "descripcion": "PIÑA PORCIONADA 130GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1098, "descripcion": "FRUTILLA PORCIONADA 130GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1099, "descripcion": "ESPINACA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1100, "descripcion": "ALBAHACA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1101, "descripcion": "CEBOLLA BLANCA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1102, "descripcion": "BROCOLI", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1103, "descripcion": "AJO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1104, "descripcion": "PAPALIZA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1105, "descripcion": "CAROTE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1106, "descripcion": "RABANO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1107, "descripcion": "ZANAHORIA BEBE", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1108, "descripcion": "CEBOLLIN", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1109, "descripcion": "PEREJIL", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1110, "descripcion": "ROMERO SECO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1111, "descripcion": "OREGANO SECO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1112, "descripcion": "TOMILLO SECO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1113, "descripcion": "MANI CRUDO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1114, "descripcion": "NUECES", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1115, "descripcion": "GARBANZOS CRUDO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1116, "descripcion": "QUINUA NEGRA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1117, "descripcion": "QUINUA BLANCA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1118, "descripcion": "BANANA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1119, "descripcion": "PECHUGA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1120, "descripcion": "POLLO ENTERO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1121, "descripcion": "BOLLO GRANDE", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1122, "descripcion": "FIDEO 4KG", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1123, "descripcion": "POLLO ENRROLLADO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1124, "descripcion": "GORDON BLU", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1125, "descripcion": "QUESO MOZZARELLA BARRA", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1126, "descripcion": "QUESO MOZZARELLA LAMINADO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1127, "descripcion": "QUESO CHEDDAR LAMINADO", "unidad_medida": "KG", "categoria": "COCINA"},
    {"codigo": 1128, "descripcion": "CROQUETAS DE JAMON", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1129, "descripcion": "EXTRACTO DE TOMATE 140GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1130, "descripcion": "PAPA PORCIONADA 140GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1131, "descripcion": "POMODORO", "unidad_medida": "LTS", "categoria": "COCINA"},
    {"codigo": 1132, "descripcion": "PESTO 300GR", "unidad_medida": "UND", "categoria": "COCINA"},
    {"codigo": 1133, "descripcion": "HAMBURGUESA 160GR", "unidad_medida": "UND", "categoria": "COCINA"},

    # --- BEBIDAS Y BARRA ---
    {"codigo": 2001, "descripcion": "AGUA CON GAS 2 L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2002, "descripcion": "AGUA CON GAS 500 ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2003, "descripcion": "AGUA SIN GAS 500 ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2004, "descripcion": "AGUA TONICA", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2005, "descripcion": "APEROL", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2006, "descripcion": "AQUARIUS POMELO 3 L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2007, "descripcion": "ARANDANOS", "unidad_medida": "KG", "categoria": "BARRA"},
    {"codigo": 2008, "descripcion": "BITTER CÍTRICO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2009, "descripcion": "BITTER HERBAL", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2010, "descripcion": "BLUE CURACAO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2011, "descripcion": "BUDWEISER", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2012, "descripcion": "CAFE JAQAKU 2 KG MEDIO", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2013, "descripcion": "CAMPARI", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2014, "descripcion": "CERVEZA DE JENGIBRE", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2015, "descripcion": "COCA COLA 3L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2016, "descripcion": "COCA COLA 2 L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2017, "descripcion": "COCA COLA 500ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2018, "descripcion": "COCA COLA ZERO 500ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2019, "descripcion": "COLORANTE AZUL", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2020, "descripcion": "COLORANTE ROJO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2021, "descripcion": "COLORANTE AMARILLO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2022, "descripcion": "COLORANTE VERDE", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2023, "descripcion": "CORONA", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2024, "descripcion": "DEL VALLE 3L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2025, "descripcion": "ESPUMOSO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2026, "descripcion": "FANTA 500ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2027, "descripcion": "FERNET", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2028, "descripcion": "GIN", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2029, "descripcion": "GINGER ALE", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2030, "descripcion": "GRANADINA", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2031, "descripcion": "HEINEKEN", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2032, "descripcion": "HIELO", "unidad_medida": "KG", "categoria": "BARRA"},
    {"codigo": 2033, "descripcion": "HUARI", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2034, "descripcion": "JUGO DE PIÑA", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2035, "descripcion": "LICOR CAFÉ", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2036, "descripcion": "LICOR CHOCOLATE", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2037, "descripcion": "LICOR DURAZNO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2038, "descripcion": "LICOR MENTA", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2039, "descripcion": "PURA VIDA PIÑA 2 L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2040, "descripcion": "RON", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2041, "descripcion": "RON BLANCO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2042, "descripcion": "SINGANI", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2043, "descripcion": "SPRITE 3 L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2044, "descripcion": "SPRITE 500 ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2045, "descripcion": "STELLA", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2046, "descripcion": "TE CLASICO", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2047, "descripcion": "TE FRUTOS ROJOS", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2048, "descripcion": "TE TRIMATE", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2049, "descripcion": "TEQUILA JARANA", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2050, "descripcion": "TRIPLE SEC", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2051, "descripcion": "VERMOUTH", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2052, "descripcion": "VINAGRE 5L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2053, "descripcion": "VINO", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2054, "descripcion": "VIOLET 180GR", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2055, "descripcion": "VODKA", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2056, "descripcion": "WHISKEY BLACK LABEL", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2057, "descripcion": "WHISKEY DOBLE V", "unidad_medida": "LTS", "categoria": "BARRA"},
    {"codigo": 2058, "descripcion": "CAFE JAQAKU 2 KG OSCURO", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2059, "descripcion": "JAGERMEISTER 1L", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2060, "descripcion": "JAGERMEISTER 500ML", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2061, "descripcion": "AMSTEL", "unidad_medida": "UND", "categoria": "BARRA"},
    {"codigo": 2062, "descripcion": "HIERBA BUENA", "unidad_medida": "KG", "categoria": "BARRA"},

    # --- INSUMOS / LIMPIEZA ---
    {"codigo": 3001, "descripcion": "BOLSITAS DE AZUCAR", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3002, "descripcion": "ROLLO DE PAPEL TOALLA", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3003, "descripcion": "PAPEL HIGENICO NACIONAL", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3004, "descripcion": "PAPEL TOALLA INTERFOLIADA", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3005, "descripcion": "SERVILLETA NACIONAL CLASSIC", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3006, "descripcion": "LAVAVAJILLAS VERDE 5L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3007, "descripcion": "LAVANDINA 3.8L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3008, "descripcion": "CITRONELA AMARILLA", "unidad_medida": "LTS", "categoria": "INSUMOS"},
    {"codigo": 3009, "descripcion": "JABON LIQUIDO PARA MANOS 5L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3010, "descripcion": "LIMPIA VIDRIOS 5L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3011, "descripcion": "SACA GRASA 5L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3012, "descripcion": "SACA GRASA 1L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3013, "descripcion": "ESPONJA", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3014, "descripcion": "QUITA SARRO 1L", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3015, "descripcion": "TRAPO ROJO LIMPIEZA", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3016, "descripcion": "PASTILLA DE BAÑO", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3017, "descripcion": "MOPA MICROFIBRA", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3018, "descripcion": "AMBIENTADOR AROMATIZANTE", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3019, "descripcion": "BOMBRIL", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3020, "descripcion": "SODA CAUSTICA", "unidad_medida": "KG", "categoria": "INSUMOS"},
    {"codigo": 3021, "descripcion": "TRAPO PISO PLOMO", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3022, "descripcion": "MARTILLO", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3023, "descripcion": "LLAVE DE GAS", "unidad_medida": "UND", "categoria": "INSUMOS"},
    {"codigo": 3024, "descripcion": "ALCOHOL GUABIRA", "unidad_medida": "LTS", "categoria": "INSUMOS"},

    # --- EMPAQUES Y VASOS ---
    {"codigo": 4001, "descripcion": "BALAS", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4002, "descripcion": "COPA MARTINI", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4003, "descripcion": "COPA PEQUEÑA", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4004, "descripcion": "COPA TULIPAN", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4005, "descripcion": "COPA VINO GRANDE", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4006, "descripcion": "OTROS VASOS", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4007, "descripcion": "TASA NORMAL", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4008, "descripcion": "VASO BASE REDONDA", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4009, "descripcion": "VASO DISEÑO CUADRADO", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4010, "descripcion": "VASO LARGO", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4011, "descripcion": "VASO MEDIANO", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4012, "descripcion": "VASO PUNTITOS", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4013, "descripcion": "VASO SHOT", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4014, "descripcion": "VASO SHOT PEQUEÑO", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4015, "descripcion": "VASO WHISKEY", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4016, "descripcion": "COPA CHOCOLATE", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4017, "descripcion": "TAZA NORMAL", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4018, "descripcion": "TAZA CAFÉ", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4019, "descripcion": "ENVASE BOX 23X14", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4020, "descripcion": "BOMBILLA NEGRA", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4021, "descripcion": "BOLSA AZUL 60X80 ISI", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4022, "descripcion": "BOLSA NEGRA GRANDE 140X90", "unidad_medida": "UND", "categoria": "EMPAQUES"},
    {"codigo": 4023, "descripcion": "BOLSA BLANCA PEQUEÑA 27X48", "unidad_medida": "UND", "categoria": "EMPAQUES"},
        ]

        if not PRODUCTOS_A_CARGAR:
            self.stdout.write(self.style.WARNING('La lista PRODUCTOS_A_CARGAR está vacía. Abre el archivo y pega tus productos.'))
            return

        creados = 0
        actualizados = 0

        for item in PRODUCTOS_A_CARGAR:
            # Usamos update_or_create para que si el código ya existe, solo actualice los demás campos.
            # Así puedes correr este comando varias veces sin duplicar datos (evita el error unique constraint).
            producto, created = Producto.objects.update_or_create(
                codigo=item['codigo'],
                defaults={
                    'descripcion': item['descripcion'],
                    'unidad_medida': item['unidad_medida'],
                    'categoria': item['categoria'],
                    'stock_minimo': item.get('stock_minimo', 0.00)
                }
            )
            
            if created:
                creados += 1
            else:
                actualizados += 1

        self.stdout.write(self.style.SUCCESS(f'¡Carga finalizada! Creados: {creados} | Actualizados: {actualizados}'))
